mongo:
  image: mongo:latest
  volumes: 
    - /data/db/mongo
  ports:
    - "27027:27017"
redis:
  image: redis
  volumes: 
    - /data/db/redis
  ports: 
    - "6379:6379"
    services:
  mongo-hotels:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/
    depends_on:
      - mongo-hotels

  backend:
    image: node:20.11
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - PORT=4000
      - MONGO_CONNECTION=mongodb://localhost:27017/hotels
    ports:
      - 4000:4000
    command: npm run start:dev
    depends_on:
      - mongo-hotels
